### PR TITLE
All dialogs wrapped in DialogFragments

### PR DESCRIPTION
**Pull request by trikaphundo**
Dialogs don't disappear anymore on configuration changes. issue #22 

1. Added a new class, "AlertDialogFragment" which is well documented. All dialogs in the app use now this class.
2. I tried to stick to your coding style
3. I tried to mess with the code as less as possible, that is, keep changes at minimum.
4. I extensively documented the new class

Feel free to tell, correct or suggest anything.

### CODE REVIEW

**Comment by stovocor** [comment]
Thank you very much for your pull request, at a first glance the code looks very good and I am confident that it can be merged without any changes.

I am going to test it in the next few days, merge the pull request and release a new version.

**Comment by trikaphundo** [comment]
After creating this pull request I pushed more changes to the merging branch instead of creating a new one... I hope this causes no problems when merging.

I am very new to CVSs; excuse my ignorance ^^'

**Comment by stovocor** [comment]
No problem at all. Do you mind if I squash all your commits into a single one?

**Comment by trikaphundo** [comment]
Yes, go ahead, and sorry ^^'. Fortunately the fix for #24 is quick to review.
Guten abend!

**Comment by stovocor** [comment]
I have merged this branch manually, therefore closing this pull request. Thanks again for your help!

**Pull request closed without merging**
